name: "Continuous Integration"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "tephida/.github/.github/workflows/continuous-integration.yml@1.0"
    with:
      php-versions: '["8.0", "8.1"]'